import { 
  Tournament, 
  Registration, 
  Payment, 
  Match,
  LeaderboardEntry,
  MarketplaceListing,
  SupportTicket,
  Notification,
  DashboardStats,
  GameRoom,
  Reward,
  User 
} from '@/types';

// Mock Tournaments
export const mockTournaments: Tournament[] = [
  {
    id: '1',
    title: 'FIFA 24 Champions League',
    description: 'The ultimate FIFA 24 tournament for the best players in Kenya. Compete against the top gamers and prove your skills!',
    game: 'fifa',
    format: 'single_elimination',
    status: 'live',
    entryFee: 500,
    prizePool: 50000,
    maxParticipants: 64,
    currentParticipants: 64,
    startDate: new Date(),
    registrationDeadline: new Date(Date.now() - 86400000),
    rules: '1. All matches are played on PS5\n2. 6-minute halves\n3. No custom formations allowed\n4. Random team selection in finals',
    imageUrl: '/fifa-tournament.jpg',
    createdBy: 'admin',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
  {
    id: '2',
    title: 'Call of Duty Warzone Battle',
    description: 'Squad up and dominate in this epic Warzone tournament. Biggest prize pool of the month!',
    game: 'cod',
    format: 'round_robin',
    status: 'registration_open',
    entryFee: 1000,
    prizePool: 100000,
    maxParticipants: 100,
    currentParticipants: 67,
    startDate: new Date(Date.now() + 3 * 86400000),
    registrationDeadline: new Date(Date.now() + 2 * 86400000),
    rules: '1. Squads of 4\n2. BR mode only\n3. No aim assist restrictions\n4. Highest placement wins',
    createdBy: 'admin',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date(),
  },
  {
    id: '3',
    title: 'PUBG Mobile Masters',
    description: 'Mobile gaming at its finest. Show your PUBG skills and win big!',
    game: 'pubg',
    format: 'swiss',
    status: 'upcoming',
    entryFee: 300,
    prizePool: 25000,
    maxParticipants: 50,
    currentParticipants: 23,
    startDate: new Date(Date.now() + 7 * 86400000),
    registrationDeadline: new Date(Date.now() + 5 * 86400000),
    rules: '1. Classic mode\n2. Erangel map\n3. Solo queue\n4. Points based on kills and placement',
    createdBy: 'admin',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date(),
  },
  {
    id: '4',
    title: 'Fortnite Zero Build Championship',
    description: 'No building, pure shooting skills. The ultimate test of aim and strategy!',
    game: 'fortnite',
    format: 'single_elimination',
    status: 'registration_open',
    entryFee: 200,
    prizePool: 15000,
    maxParticipants: 32,
    currentParticipants: 28,
    startDate: new Date(Date.now() + 2 * 86400000),
    registrationDeadline: new Date(Date.now() + 86400000),
    rules: '1. Zero Build mode\n2. Solo matches\n3. Best of 3 format\n4. Victory Royale = instant win',
    createdBy: 'admin',
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date(),
  },
  {
    id: '5',
    title: 'Apex Legends Pro Series',
    description: 'Fast-paced action with the legends. Trios tournament with massive rewards!',
    game: 'apex',
    format: 'double_elimination',
    status: 'completed',
    entryFee: 750,
    prizePool: 75000,
    maxParticipants: 60,
    currentParticipants: 60,
    startDate: new Date(Date.now() - 7 * 86400000),
    endDate: new Date(Date.now() - 1 * 86400000),
    registrationDeadline: new Date(Date.now() - 10 * 86400000),
    rules: '1. Ranked Arena mode\n2. Trios only\n3. All legends allowed\n4. Standard competitive settings',
    createdBy: 'admin',
    createdAt: new Date('2023-12-20'),
    updatedAt: new Date(),
  },
  {
    id: '6',
    title: 'Valorant Showdown',
    description: 'Tactical shooter excellence. 5v5 competitive matches for glory!',
    game: 'valorant',
    format: 'single_elimination',
    status: 'registration_open',
    entryFee: 500,
    prizePool: 40000,
    maxParticipants: 16,
    currentParticipants: 12,
    startDate: new Date(Date.now() + 5 * 86400000),
    registrationDeadline: new Date(Date.now() + 4 * 86400000),
    rules: '1. Standard competitive settings\n2. Map veto system\n3. Best of 3 until finals\n4. Finals are Best of 5',
    createdBy: 'admin',
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date(),
  },
];

// Mock Registrations
export const mockRegistrations: Registration[] = [
  {
    id: '1',
    tournamentId: '1',
    userId: '1',
    status: 'confirmed',
    paymentId: '1',
    gameHandle: 'ProGamer#1234',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date(),
  },
  {
    id: '2',
    tournamentId: '2',
    userId: '1',
    status: 'pending',
    gameHandle: 'ProGamer#1234',
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date(),
  },
];

// Mock Payments
export const mockPayments: Payment[] = [
  {
    id: '1',
    userId: '1',
    tournamentId: '1',
    amount: 500,
    method: 'mpesa',
    status: 'verified',
    transactionCode: 'QWE12345RT',
    verifiedBy: 'admin',
    verifiedAt: new Date('2024-01-15'),
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date(),
  },
  {
    id: '2',
    userId: '2',
    tournamentId: '2',
    amount: 1000,
    method: 'mpesa',
    status: 'pending',
    transactionCode: 'ABC67890XY',
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date(),
  },
  {
    id: '3',
    userId: '3',
    tournamentId: '3',
    amount: 300,
    method: 'mpesa',
    status: 'pending',
    transactionCode: 'MNO11223ZZ',
    createdAt: new Date('2024-01-19'),
    updatedAt: new Date(),
  },
];

// Mock Matches
export const mockMatches: Match[] = [
  {
    id: '1',
    tournamentId: '1',
    round: 1,
    matchNumber: 1,
    player1Id: '1',
    player2Id: '2',
    player1Score: 3,
    player2Score: 1,
    winnerId: '1',
    status: 'completed',
    scheduledAt: new Date(),
    completedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    tournamentId: '1',
    round: 1,
    matchNumber: 2,
    player1Id: '3',
    player2Id: '4',
    status: 'live',
    scheduledAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    tournamentId: '1',
    round: 1,
    matchNumber: 3,
    player1Id: '5',
    player2Id: '6',
    status: 'scheduled',
    scheduledAt: new Date(Date.now() + 3600000),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Mock Leaderboard
export const mockLeaderboard: LeaderboardEntry[] = [
  { rank: 1, userId: '1', username: 'ProGamer254', avatarUrl: '', gameHandle: 'ProGamer#1234', wins: 45, losses: 5, points: 4500, earnings: 125000, tournamentsPlayed: 15 },
  { rank: 2, userId: '2', username: 'KillerInstinct', avatarUrl: '', gameHandle: 'Killer#5678', wins: 42, losses: 8, points: 4200, earnings: 98000, tournamentsPlayed: 14 },
  { rank: 3, userId: '3', username: 'NairobiNinja', avatarUrl: '', gameHandle: 'Ninja#9012', wins: 38, losses: 12, points: 3800, earnings: 75000, tournamentsPlayed: 16 },
  { rank: 4, userId: '4', username: 'EliteSniper', avatarUrl: '', gameHandle: 'Sniper#3456', wins: 35, losses: 15, points: 3500, earnings: 62000, tournamentsPlayed: 13 },
  { rank: 5, userId: '5', username: 'BeastMode', avatarUrl: '', gameHandle: 'Beast#7890', wins: 33, losses: 17, points: 3300, earnings: 55000, tournamentsPlayed: 15 },
  { rank: 6, userId: '6', username: 'ShadowStrike', avatarUrl: '', gameHandle: 'Shadow#1122', wins: 30, losses: 20, points: 3000, earnings: 48000, tournamentsPlayed: 14 },
  { rank: 7, userId: '7', username: 'ThunderBolt', avatarUrl: '', gameHandle: 'Thunder#3344', wins: 28, losses: 22, points: 2800, earnings: 42000, tournamentsPlayed: 12 },
  { rank: 8, userId: '8', username: 'VenomViper', avatarUrl: '', gameHandle: 'Venom#5566', wins: 26, losses: 24, points: 2600, earnings: 38000, tournamentsPlayed: 13 },
  { rank: 9, userId: '9', username: 'RapidFire', avatarUrl: '', gameHandle: 'Rapid#7788', wins: 24, losses: 26, points: 2400, earnings: 32000, tournamentsPlayed: 11 },
  { rank: 10, userId: '10', username: 'StealthKing', avatarUrl: '', gameHandle: 'Stealth#9900', wins: 22, losses: 28, points: 2200, earnings: 28000, tournamentsPlayed: 12 },
];

// Mock Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  totalUsers: 1542,
  totalTournaments: 48,
  activeTournaments: 6,
  pendingPayments: 23,
  totalRevenue: 2450000,
  todayRevenue: 45000,
  newUsersToday: 18,
  liveTournaments: 2,
};

// Mock Game Rooms
export const mockGameRooms: GameRoom[] = [
  {
    id: '1',
    tournamentId: '1',
    matchId: '2',
    roomCode: 'FLEX-2024-001',
    password: 'battle123',
    platform: 'playstation',
    createdAt: new Date(),
    expiresAt: new Date(Date.now() + 3600000),
  },
];

// Mock Rewards
export const mockRewards: Reward[] = [
  {
    id: '1',
    userId: '1',
    tournamentId: '5',
    type: 'prize',
    amount: 25000,
    description: 'First Place - Apex Legends Pro Series',
    status: 'claimed',
    claimedAt: new Date(Date.now() - 2 * 86400000),
    createdAt: new Date(Date.now() - 2 * 86400000),
  },
  {
    id: '2',
    userId: '1',
    type: 'bonus',
    amount: 500,
    description: 'Welcome Bonus',
    status: 'pending',
    expiresAt: new Date(Date.now() + 7 * 86400000),
    createdAt: new Date(),
  },
];

// Mock Marketplace Listings
export const mockMarketplaceListings: MarketplaceListing[] = [
  {
    id: '1',
    sellerId: '2',
    title: 'Pro FIFA Account - Division 1',
    description: 'Fully loaded FIFA account with all top players. Ultimate Team ready.',
    category: 'account',
    price: 15000,
    status: 'active',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date(),
  },
  {
    id: '2',
    sellerId: '3',
    title: '1-Hour Gaming Coaching Session',
    description: 'Learn pro strategies from a top-ranked player. Available for FIFA, COD, or Apex.',
    category: 'coaching',
    price: 2000,
    status: 'active',
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date(),
  },
];

// Mock Support Tickets
export const mockSupportTickets: SupportTicket[] = [
  {
    id: '1',
    userId: '1',
    subject: 'Payment not reflecting',
    description: 'I made a payment 2 hours ago but my registration is still pending.',
    status: 'open',
    priority: 'high',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: '1',
    userId: '1',
    type: 'tournament',
    title: 'Tournament Starting Soon!',
    message: 'FIFA 24 Champions League starts in 30 minutes. Get ready!',
    isRead: false,
    actionUrl: '/tournaments/1',
    createdAt: new Date(),
  },
  {
    id: '2',
    userId: '1',
    type: 'payment',
    title: 'Payment Verified',
    message: 'Your payment for FIFA 24 Champions League has been verified.',
    isRead: true,
    createdAt: new Date(Date.now() - 86400000),
  },
];

// Mock Users for admin view
export const mockAllUsers: User[] = [
  {
    id: '1',
    phone: '0712345678',
    username: 'ProGamer254',
    email: 'progamer@example.com',
    gameHandle: 'ProGamer#1234',
    walletBalance: 5000,
    role: 'user',
    isVerified: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date(),
  },
  {
    id: '2',
    phone: '0723456789',
    username: 'KillerInstinct',
    email: 'killer@example.com',
    gameHandle: 'Killer#5678',
    walletBalance: 3200,
    role: 'user',
    isVerified: true,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date(),
  },
  {
    id: '3',
    phone: '0734567890',
    username: 'NairobiNinja',
    email: 'ninja@example.com',
    gameHandle: 'Ninja#9012',
    walletBalance: 1500,
    role: 'user',
    isVerified: false,
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date(),
  },
];
